ROLE_USER = "user"
ROLE_JOURNALIST = "journalist"
ROLE_ADMIN = "admin"

NEWS_DRAFT = "draft"
NEWS_PENDING = "pending"
NEWS_PUBLISHED = "published"
NEWS_REJECTED = "rejected"

ALL_ROLES = {ROLE_USER, ROLE_JOURNALIST, ROLE_ADMIN}
ALL_STATUSES = {NEWS_DRAFT, NEWS_PENDING, NEWS_PUBLISHED, NEWS_REJECTED}
